In [15]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib

In [16]:
# file paths and file names
col_name_old = 'Flooded Area Impacted'
path_main = '/Users/srilakshmi/Desktop/Thesis/Data/District-level/Flooded-Area/'
name_folder_data = 'Data-Recurrence/'
path_data = path_main+name_folder_data
name_output_file = 'District-level_Flooded_Area_Recurrence.csv'

In [17]:
# data cleaning functions

def clean_csv_recurrence(string):
    
    df = pd.read_csv(name_folder_data+string, header=0)
    df = df.drop_duplicates()
    df = df.rename(columns={col_name_old: string[48:54]})
    df = df.sort_values(by=['Region'])

    return df

def special_merge(left,right):
    merged = left.set_index('Region').join(right.set_index('Region')) # merged file 0 and file 1 together    
    merged.index.name = 'Region'
    merged.reset_index(inplace=True)
    
    return merged

In [24]:
# get list of file names
files = [f for f in listdir(path_data) if isfile(join(path_data, f))]
files.sort(reverse = False)
files

['Flooded Area Impacted in Ghana Ghana_Recurrence_02Year.csv',
 'Flooded Area Impacted in Ghana Ghana_Recurrence_05Year.csv',
 'Flooded Area Impacted in Ghana Ghana_Recurrence_10Year.csv',
 'Flooded Area Impacted in Ghana Ghana_Recurrence_15Year.csv',
 'Flooded Area Impacted in Ghana Ghana_Recurrence_20Year.csv']

In [25]:
# merge files
for i in range(0, 1):
    x = clean_csv_recurrence(files[i])
    y = clean_csv_recurrence(files[i+1])
    merged = special_merge(left = x, right = y)
    
for i in range(2, 5):
    z = clean_csv_recurrence(files[i])
    merged = special_merge(left = merged, right = z)
    i += 1

merged

                         Region  02Year  05Year  10Year  15Year  20Year
0    Abura / Asebu / Kwamankese    0.00    0.03    0.13    0.18    0.24
1              Accra Metropolis    0.03    0.23    0.30    0.33    0.41
2                      Ada East   24.27   37.05   39.18   40.33   42.67
3                      Ada West   33.67   43.25   45.84   47.15   49.39
4                        Adaklu    0.00    0.13    0.18    0.20    0.23
..                          ...     ...     ...     ...     ...     ...
211                  West Gonja    1.16    2.32    4.73    6.41    9.08
212               West Mamprusi    6.39   15.84   61.95   91.63  129.07
213             Yendi Municipal    2.67    4.16    5.97    7.30    9.88
214                  Yilo Krobo    0.02    0.09    0.29    0.48    0.65
215                     Zabzugu    2.88    3.96    4.58    5.19    6.31

[216 rows x 6 columns]

In [26]:
# save file to disk

merged.to_csv(path_main+name_output_file, index = False, header=True)