In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib

In [2]:
# file paths and names
path_input_1 = '/Users/srilakshmi/Desktop/Thesis/Data/District-level/People/Output/'
name_input_file_1 = 'District-level_People_Recurrence.csv'

path_input_2 = '/Users/srilakshmi/Desktop/Thesis/Data/District-level/People/Data-Total-Pop/'
name_input_file_2 = 'Impacts-Ghana_MaxFlood_20200715_20201014.csv'

path_output = '/Users/srilakshmi/Desktop/Thesis/Treatment-Control-Assignment/Avg-Perc-Impacted-Per-Year-Recurrence/'
name_output_file = 'Avg-Perc-Impacted-Per-Year-Recurrence_People.csv'

In [3]:
# read in total populations data
tot_pop = pd.read_csv(path_input_2+name_input_file_2, header=0)

colnames = []
for col in tot_pop.columns:
    colnames.append(col)

tot_pop = tot_pop.dropna(subset=[colnames[2]])
tot_pop = tot_pop[[colnames[1], colnames[2]]]
tot_pop = tot_pop.rename(columns={colnames[1]: "Region", colnames[2]: "Total Pop"})

# merge with existing file
merged = pd.read_csv(path_input_1+name_input_file_1, header=0)

new_merge = tot_pop.set_index('Region').join(merged.set_index('Region')) # merged file 0 and file 1 together
new_merge = new_merge.sort_values(by=['Region'])

new_merge.index.name = 'Region'
new_merge.reset_index(inplace=True)

In [4]:
# recalculate totals
perc_imp = pd.DataFrame({'Region': list(new_merge['Region'])})

perc_imp['02Year'] = list(new_merge['02Year']/new_merge['Total Pop'])
perc_imp['05Year'] = list(new_merge['05Year']/new_merge['Total Pop'])
perc_imp['10Year'] = list(new_merge['10Year']/new_merge['Total Pop'])
perc_imp['15Year'] = list(new_merge['15Year']/new_merge['Total Pop'])
perc_imp['20Year'] = list(new_merge['20Year']/new_merge['Total Pop'])

perc_imp

,Region,02Year,05Year,10Year,15Year,20Year
0,Abura / Asebu / Kwamankese,0.000000,0.000000,0.000000,0.000000,0.000000
1,Accra Metropolis,0.000022,0.000194,0.000439,0.000583,0.000695
2,Ada East,0.000000,0.000937,0.002695,0.003843,0.004804
3,Ada West,0.000248,0.005295,0.009073,0.011045,0.013637
4,Adaklu,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...
211,West Gonja,0.000000,0.000000,0.000000,0.000000,0.000000
212,West Mamprusi,0.000066,0.000132,0.000263,0.000507,0.000573
213,Yendi Municipal,0.000000,0.000000,0.000181,0.000181,0.000181
214,Yilo Krobo,0.000000,0.000000,0.000000,0.000000,0.000000
215,Zabzugu,0.000000,0.000000,0.000000,0.000000,0.000000

In [5]:
# save file to disk

perc_imp.to_csv(path_output+name_output_file, index = False, header=True)