In [33]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib
import sys

# insert at 1, 0 is the script path (or '' in REPL)
path_mod = '/Users/srilakshmi/Desktop/Thesis/04-Data-Analysis-Results/00-Data-Sources/00-Cloud-to-Street/01-District-level/'
sys.path.insert(1, path_mod)

import clean

In [34]:
# file and column names used
col_name_old = "People Impacted"
monitor_name_pos_left = 39
monitor_name_pos_right = 56
historic_name_pos_left = 40
historic_name_pos_right = 57

# file paths and file names
path_input = '/Users/srilakshmi/Desktop/Thesis/04-Data-Analysis-Results/00-Data-Sources/00-Cloud-to-Street/01-District-level/People/Data-NRT/'

path_output = '/Users/srilakshmi/Desktop/Thesis/04-Data-Analysis-Results/00-Data-Sources/00-Cloud-to-Street/01-District-level/People/Output/'
name_output_file = 'District-level_People_NRT.csv'

In [35]:
# get list of file names
files = [f for f in listdir(path_input) if isfile(join(path_input, f))]
files=files[1:]
files

['People Impacted in Ghana Ghana_Monitor_20200902_20200909.csv',
 'People Impacted in Ghana Ghana_Historic_20190901_20190920.csv',
 'People Impacted in Ghana Ghana_Monitor_20200930_20201007.csv',
 'People Impacted in Ghana Ghana_Monitor_20200916_20200923.csv',
 'People Impacted in Ghana Ghana_Monitor_20200715_20200722.csv',
 'People Impacted in Ghana Ghana_Monitor_20200923_20200930.csv',
 'People Impacted in Ghana Ghana_Monitor_20200722_20200729.csv',
 'People Impacted in Ghana Ghana_Monitor_20200826_20200902.csv',
 'People Impacted in Ghana Ghana_Monitor_20200819_20200826.csv',
 'People Impacted in Ghana Ghana_Monitor_20200805_20200812.csv',
 'People Impacted in Ghana Ghana_Monitor_20200909_20200916.csv',
 'People Impacted in Ghana Ghana_Monitor_20201014_20201021.csv',
 'People Impacted in Ghana Ghana_Historic_20180815_20181015.csv',
 'People Impacted in Ghana Ghana_Monitor_20200812_20200819.csv']

In [36]:
# merge csv files

for i in range(0, 1):
    x = clean.clean_csv_monitor(col_name_old, path_input, files[i], monitor_name_pos_left, monitor_name_pos_right)
    y = clean.clean_csv_monitor(col_name_old, path_input, files[i+1], monitor_name_pos_left, monitor_name_pos_right)
    merged = clean.special_merge(left = x, right = y)

for i in range(2, 3):
    z = clean.clean_csv_historic(col_name_old, path_input, files[i], historic_name_pos_left, historic_name_pos_right)
    merged = clean.special_merge(left = merged, right = z)
    
for i in range(3, 13):
    z = clean.clean_csv_monitor(col_name_old, path_input, files[i], monitor_name_pos_left, monitor_name_pos_right)
    merged = clean.special_merge(left = merged, right = z)
    i += 1
    
for i in range(13,14):
    z = clean.clean_csv_historic(col_name_old, path_input, files[i], historic_name_pos_left, historic_name_pos_right)
    merged = clean.special_merge(left = merged, right = z)
    
# for i in range(14,15):
#     z = clean.clean_csv_monitor(col_name_old, path_input, files[i], monitor_name_pos_left, monitor_name_pos_right)
#     merged = clean.special_merge(left = merged, right = z)

merged

,Region,20200902_20200909,_20190901_2019092,0200930_20201007.,20200916_20200923,20200715_20200722,20200923_20200930,20200722_20200729,20200826_20200902,20200819_20200826,20200805_20200812,20200909_20200916,20201014_20201021,_20180815_2018101,0200812_20200819.
0,Abura / Asebu / Kwamankese,0,540,0,0,0,80,0,0,0,16,0,0,0,0.0
1,Accra Metropolis,162,8143,205,0,496,0,164,0,0,106,0,283,0,82.0
2,Ada East,550,802,0,0,40,0,50,0,0,62,100,840,0,104.0
3,Ada West,334,1338,0,0,20,0,0,0,30,216,0,2073,0,270.0
4,Adaklu,0,322,0,0,0,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,West Gonja,0,22,11,0,11,0,0,0,0,0,0,0,22,0.0
212,West Mamprusi,125,243,165,155,50,142,10,26,16,0,206,76,1215,140.0
213,Yendi Municipal,13,13,845,14,0,13,39,0,0,0,13,104,52,26.0
214,Yilo Krobo,0,35,0,0,0,0,0,0,0,0,0,105,0,0.0
215,Zabzugu,0,110,112,0,32,16,0,0,0,0,0,0,1173,16.0

In [37]:
# save file to disk

merged.to_csv(path_output+name_output_file, index = False, header=True)

In [47]:
merged['People_Sum_2020']=merged.sum(axis=1)

x = pd.concat((merged['Region'], merged['People_Sum_2020']),axis=1)

In [48]:
path_totals = '/Users/srilakshmi/Desktop/Thesis/04-Data-Analysis-Results/00-Data-Sources/00-Cloud-to-Street/01-District-level/Totals/'
dfx = pd.read_csv(path_totals+'population-total.csv')

totals = dfx[[dfx.columns[1], dfx.columns[2]]]
totals.columns = ['Region', 'total_population']
totals = totals.dropna(subset=['total_population'])[['Region', 'total_population']]

In [58]:
df = x.merge(totals, on=['Region'])

df.columns = ['Region', 'Pop_Sum_2020', 'Pop_Total']

df['Perc_Affected']=df['Pop_Sum_2020']/df['Pop_Total']

df.sort_values(by='Perc_Affected',ascending=False)

                           Region  Pop_Sum_2020  Pop_Total  Perc_Affected
90                  Gonja Central       40185.0    94866.0       0.423597
111  Komenda Edna Eguafo / Abirem       55070.0   162663.0       0.338553
3                        Ada West       21405.0    72523.0       0.295148
117                   Krachi West       20085.0    78083.0       0.257226
80                         Ekumfi       15085.0    67707.0       0.222798
..                            ...           ...        ...            ...
188                    Tano North           0.0    90522.0       0.000000
13                Ahafo Ano North           0.0   115019.0       0.000000
74                    Dormaa West           0.0    43046.0       0.000000
72                    Dormaa East           0.0    64839.0       0.000000
155             Offinso Municipal           0.0    71115.0       0.000000

[216 rows x 4 columns]