In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib

In [2]:
# file and column names used
col_name_old = "People Impacted"
monitor_name_pos_left = 39
monitor_name_pos_right = 56
historic_name_pos_left = 40
historic_name_pos_right = 57

# file paths and file names
path_main = '/Users/srilakshmi/Desktop/Thesis/Data/District-level/People/'
name_folder_data = 'Data-NRT/'
path_data = path_main+name_folder_data
name_output_file = 'District-level_People_NRT.csv'

In [3]:
# data cleaning functions

def clean_csv_monitor(string):
    
    df = pd.read_csv(name_folder_data+string, header=0)
    df = df.drop_duplicates()
    df = df.rename(columns={col_name_old: string[monitor_name_pos_left:monitor_name_pos_right]})
    df = df.sort_values(by=['Region'])
    
    return df

def clean_csv_historic(string):
    
    df = pd.read_csv(name_folder_data+string, header=0)
    df = df.drop_duplicates()
    df = df.rename(columns={col_name_old: string[historic_name_pos_left:historic_name_pos_right]})
    df = df.sort_values(by=['Region'])
    
    return df

def special_merge(left,right):
    merged = left.set_index('Region').join(right.set_index('Region')) # merged file 0 and file 1 together    
    merged.index.name = 'Region'
    merged.reset_index(inplace=True)
    
    return merged

In [4]:
# get list of file names
files = [f for f in listdir(path_data) if isfile(join(path_data, f))]
files

['People Impacted in Ghana Ghana_Monitor_20201007_20201014.csv',
 'People Impacted in Ghana Ghana_Monitor_20200902_20200909.csv',
 'People Impacted in Ghana Ghana_Historic_20190901_20190920.csv',
 'People Impacted in Ghana Ghana_Monitor_20200930_20201007.csv',
 'People Impacted in Ghana Ghana_Monitor_20200916_20200923.csv',
 'People Impacted in Ghana Ghana_Monitor_20200715_20200722.csv',
 'People Impacted in Ghana Ghana_Monitor_20200923_20200930.csv',
 'People Impacted in Ghana Ghana_Monitor_20200722_20200729.csv',
 'People Impacted in Ghana Ghana_Monitor_20200826_20200902.csv',
 'People Impacted in Ghana Ghana_Monitor_20200819_20200826.csv',
 'People Impacted in Ghana Ghana_Monitor_20200805_20200812.csv',
 'People Impacted in Ghana Ghana_Monitor_20200909_20200916.csv',
 'People Impacted in Ghana Ghana_Monitor_20201014_20201021.csv',
 'People Impacted in Ghana Ghana_Historic_20180815_20181015.csv',
 'People Impacted in Ghana Ghana_Monitor_20200812_20200819.csv']

In [5]:
# merge csv files

for i in range(0, 1):
    x = clean_csv_monitor(files[i])
    y = clean_csv_monitor(files[i+1])
    merged = special_merge(left = x, right = y)

for i in range(2, 3):
    z = clean_csv_historic(files[i])
    merged = special_merge(left = merged, right = z)
    
for i in range(3, 13):
    z = clean_csv_monitor(files[i])
    merged = special_merge(left = merged, right = z)
    i += 1
    
for i in range(13,14):
    z = clean_csv_historic(files[i])
    merged = special_merge(left = merged, right = z)
    
for i in range(14,15):
    z = clean_csv_monitor(files[i])
    merged = special_merge(left = merged, right = z)
    
merged

,Region,20201007_20201014,20200902_20200909,20190901_20190920,20200930_20201007,20200916_20200923,20200715_20200722,20200923_20200930,20200722_20200729,20200826_20200902,20200819_20200826,20200805_20200812,20200909_20200916,20201014_20201021,20180815_20181015,20200812_20200819
0,Abura / Asebu / Kwamankese,0,0,540,0,0,0,80,0,0,0,16,0,0,0,0.0
1,Accra Metropolis,332,162,8143,205,0,496,0,164,0,0,106,0,283,0,82.0
2,Ada East,0,550,802,0,0,40,0,50,0,0,62,100,840,0,104.0
3,Ada West,0,334,1338,0,0,20,0,0,0,30,216,0,2073,0,270.0
4,Adaklu,0,0,322,0,0,0,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,West Gonja,0,0,22,11,0,11,0,0,0,0,0,0,0,22,0.0
212,West Mamprusi,133,125,243,165,155,50,142,10,26,16,0,206,76,1215,140.0
213,Yendi Municipal,104,13,13,845,14,0,13,39,0,0,0,13,104,52,26.0
214,Yilo Krobo,0,0,35,0,0,0,0,0,0,0,0,0,105,0,0.0
215,Zabzugu,16,0,110,112,0,32,16,0,0,0,0,0,0,1173,16.0

In [6]:
# save file to disk

merged.to_csv(path_main+name_output_file, index = False, header=True)