In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib

In [2]:
# file paths and file names
path_input = '/Users/srilakshmi/Desktop/Thesis/Treatment-Control-Assignment/Avg-Num-Impacted-Per-Year-Recurrence/'

path_output = '/Users/srilakshmi/Desktop/Thesis/Avg-Num-Impacted-Per-Year-Recurrence/'
name_output_file = 'District_Avg_Num_Impacted_Per_Year_All.csv'

In [3]:
# get list of file names
files = [f for f in listdir(path_input) if isfile(join(path_input, f))]
files

['calculate avg num per year - flooded area.ipynb',
 'District_Avg_Num_Per_Year_Roads.csv',
 '.DS_Store',
 'District_Avg_Num_Per_Year_Flooded_Area.csv',
 'calculate avg num per year - hospitals.ipynb',
 'District_Avg_Num_Per_Year_Hospitals.csv',
 'calculate avg num per year - markets.ipynb',
 'calculate avg num per year - roads.ipynb',
 'calculate avg num per year - schools.ipynb',
 'District_Avg_Num_Per_Year_Schools.csv']

In [4]:
# merge files
for i in range(0, 1):
    x = pd.read_csv(path_input+files[i])
    y = pd.read_csv(path_input+files[i+1])
    merged = pd.merge(left=x, right=y, how='left', on='Region') 

for i in range(2, 7):
    z = pd.read_csv(path_input+files[i])
    merged = pd.merge(left=merged, right=z, how='left', on='Region')
merged

,Region,Avg Impact Per Year - Roads,Avg Impact Per Year - Flooded Area,Avg Impact Per Year - Markets,Avg Impact Per Year - Hospitals,Avg Impact Per Year - Pop,Avg Impact Per Year - Schools,Avg Impact Per Year - Crops
0,Abura / Asebu / Kwamankese,0.000000,0.022333,0.00,0.0,0.000000,0.0,0.000000
1,Juabeso,0.000000,0.000500,0.00,0.0,0.000000,0.0,0.000000
2,Suaman,0.000000,0.002000,0.00,0.0,0.000000,0.0,0.000000
3,Suhum Municipal,0.000000,0.000667,0.00,0.0,0.000000,0.0,0.000500
4,Jasikan,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...
211,Ga South,2035.066667,12.120500,0.00,0.0,276.366667,0.0,0.165333
212,Ketu South,2391.500000,8.941000,0.00,0.0,63.300000,0.1,0.834167
213,Kpandai,2980.866667,67.747833,0.00,0.0,23.466667,0.0,2.302500
214,Keta Municipal,4728.666667,58.484667,0.25,0.0,140.966667,0.2,0.202833
215,Krachi Nchumuru,8620.800000,85.231667,0.00,0.0,39.933333,0.0,1.284667

In [5]:
# organize df

colnames = list(merged.columns[1:])
myorder = [4, 6, 0, 1, 2, 3, 5]
colnames = [colnames[i] for i in myorder]

colnames.insert(0, 'Region')
colnames

['Region',
 'Avg Impact Per Year - Pop',
 'Avg Impact Per Year - Crops',
 'Avg Impact Per Year - Roads',
 'Avg Impact Per Year - Flooded Area',
 'Avg Impact Per Year - Markets',
 'Avg Impact Per Year - Hospitals',
 'Avg Impact Per Year - Schools']

In [6]:
# sort df
merged = merged[colnames]
merged = merged.sort_values(by = ['Avg Impact Per Year - Pop', 'Avg Impact Per Year - Crops'],
                            ascending = False)
merged

,Region,Avg Impact Per Year - Pop,Avg Impact Per Year - Crops,Avg Impact Per Year - Roads,Avg Impact Per Year - Flooded Area,Avg Impact Per Year - Markets,Avg Impact Per Year - Hospitals,Avg Impact Per Year - Schools
182,Gonja Central,365.683333,1.049333,148.166667,66.309000,0.00,0.0,0.0
211,Ga South,276.366667,0.165333,2035.066667,12.120500,0.00,0.0,0.0
200,East Gonja,257.983333,6.930667,398.100000,198.752333,0.00,0.0,0.0
153,Accra Metropolis,156.450000,0.000500,36.866667,0.068000,0.00,0.0,0.0
214,Keta Municipal,140.966667,0.202833,4728.666667,58.484667,0.25,0.0,0.2
...,...,...,...,...,...,...,...,...
91,Bia West,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0
100,Techiman Municipal,0.000000,0.000000,1.000000,0.000000,0.00,0.0,0.0
101,Hohoe Municipal,0.000000,0.000000,1.500000,0.000667,0.00,0.0,0.0
115,Sekyere Afram Plains North,0.000000,0.000000,4.500000,0.004667,0.00,0.0,0.0
134,Sekondi Takoradi,0.000000,0.000000,21.500000,0.017167,0.00,0.0,0.0

In [7]:
# save file to disk

merged.to_csv(path_output+name_output_file, index = False, header=True)