In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import pathlib

In [2]:
# file paths and names
path_input = '/Users/srilakshmi/Desktop/Thesis/Data/District-level/Roads/Output/'
name_input_file = 'District-level_Roads_Recurrence.csv'

path_output = '/Users/srilakshmi/Desktop/Thesis/Treatment-Control-Assignment/Avg-Num-Impacted-Per-Year-Recurrence/'
name_output_file = 'District_Avg_Num_Per_Year_Roads.csv'

In [3]:
# add in zeroes column
df = pd.read_csv(path_input+name_input_file, header=0)
zeroes = [0] * len(df)
df.insert(1, "Zeroes", zeroes, True)
df

,Region,Zeroes,02Year,05Year,10Year,15Year,20Year
0,Abura / Asebu / Kwamankese,0,0,0,0,0,0
1,Accra Metropolis,0,0,90,170,174,386
2,Ada East,0,350,790,1870,2020,2330
3,Ada West,0,620,1530,2570,3030,3410
4,Adaklu,0,0,0,0,0,0
...,...,...,...,...,...,...,...
211,West Gonja,0,0,0,180,270,546
212,West Mamprusi,0,40,139,1019,3739,13660
213,Yendi Municipal,0,9,241,541,631,930
214,Yilo Krobo,0,0,0,0,0,0
215,Zabzugu,0,11,99,129,169,249

In [4]:
# calculate average impact per year for population
return_periods = [2, 5, 10, 15, 20]
avg_impact_per_year = []

for i in range(0, len(df)):
    marg_impact_per_year = [] # collect marginal impact per year to then sum up

    for j in range(1, 6):
        x = ( df.iloc[i, j+1] - df.iloc[i, j] ) / return_periods[j-1]
        marg_impact_per_year.append(x)
        
    avg_impact_per_year.append(sum(marg_impact_per_year))

In [4]:
# add output to df
flood_risk_classification = df[['Region']]
colname = 'Avg Num Flooded Per Year - Roads'

flood_risk_classification.insert(1,colname, avg_impact_per_year, True)
flood_risk_classification = flood_risk_classification.sort_values(colname) # sort from low to high avg impact per year
flood_risk_classification

NameError: name 'avg_impact_per_year' is not defined

In [5]:
# save file to disk

flood_risk_classification.to_csv(path_output+name_output_file, index = False, header=True)